### ISSUE TITLE
Bug on base/mqi_treatment_machine_pbs.hpp

### ISSUE THREAD

**Issue by Giorgio5i6** [mghro/moquimc#10]
Hi! Thank you for your incredible work! 

I found a bug in the general PBS treatment machine class (base/mqi_treatment_machine_pbs.hpp). I provided the machine parameter from an input file and I obtained random beam positions.  In the PBS definition line 105 was missing the assignment of the _treatment_machine_ion<T>::SAD_

The following is my version of the corrected code.

Best, Giorgio Cartechini

```
pbs(const std::string filename) : cm2mm(10.0), mm2cm(0.0) {
    this->load_beamdata(filename);
    if (geometry_spec_.SAD[0] == 0)
        treatment_machine_ion<T>::SAD_[0] = std::numeric_limits<T>::infinity();
    else 
        treatment_machine_ion<T>::SAD_[0] = geometry_spec_.SAD[0];
        
    if (geometry_spec_.SAD[1] == 0)
        treatment_machine_ion<T>::SAD_[1] = std::numeric_limits<T>::infinity();
    else
        treatment_machine_ion<T>::SAD_[1] = geometry_spec_.SAD[1];
}
```

**Comment by leehoy** [comment]
Thank you for reporting this Giorgio.
We have updated the code.
